### PR TITLE
Updated Gerischer element equation and documentation to match

### PR DESCRIPTION
**Pull request by BGerwe**
Changed circuit_elements.py to reflect changes discussed in #37.  I included a common alternate definition (Used by Bernard Boukamp and others in González-Cuenca et. al [1], and Boukamp and Bouwmeester [2], among others) below the one used here.  The goal is to preempt concerns that we are not using the "correct" definition and to demonstrate the two are mathematically equivalent. Hopefully, it's not too confusing as written.

[1] [https://doi.org/10.1016/S0167-2738(02)00185-6](url)
[2] [https://doi.org/10.1002/1615-6854(200112)1:3/4%3C256::AID-FUCE256%3E3.0.CO;2-I](url)

### CODE REVIEW

**Comment by mdmurbach** [comment]
Cool! :) Looks like the flake8 issues are fixed. Now the tests are failing because the parameters we get back aren't the same format as before.

Just for future reference, you can run flake8 locally (`flake8` in the impedance.py directory). You can also run the tests locally too (`pytest` in the impedance.py directory). I think both are installable with conda.

I think we could also add a reference (maybe one for each equation) since you've already included them in the issues?

You can look at the `T` (macrohomogeneous porous electrode) element to see how to insert a link.

```rst

text text [1]

...

[1] G. Paasch, K. Micka, and P. Gersdorf,
    Electrochimica Acta, 38, 2653–2662 (1993)
    `doi: 10.1016/0013-4686(93)85083-B
    <https://doi.org/10.1016/0013-4686(93)85083-B>`_.
```

**Comment by mdmurbach** [comment]
https://github.com/ECSHackWeek/impedance.py/blob/2c62b6d0332e76ec6aca772546ddfd0bd4c911b5/impedance/tests/test_circuit_elements.py#L21-L23

If I'm doing it right, the correct test results should change to
```
[(0.09999994-6.28317911e-05j),
(0.07107755-3.42746521e-02j),
(0.0019955 -1.99391726e-03j)]]
```

**Comment by BGerwe** [comment]
Thanks for the tips on testing locally and sorry about excessive notifications I may have caused.

 I added the references and made sure it passes flake8 again. Those are the same values I got for the tests, so I've added them in with a bit higher precision. Is there anything I need to configure for `pytest`? I get a ton of errors when I try running it from terminal in my impedance.py directory.

**Comment by mdmurbach** [comment]
Great! Not sure what the issue with pytest might be. What kind of errors are you getting? Nothing wrong with using Travis as the check (just a longer wait :wink:)

**Comment by BGerwe** [comment]
image


Which I think boils down to `OSError: [WinError 87] The parameter is incorrect`. It seems that it's some error using `pytest` with  Python 3.7.4. In any case, it passed using nose.

**Comment by mdmurbach** [comment]
@all-contributors please add @BGerwe for doc

**Pull request merged**
