### PR TITLE
Changed README.md encoding to UTF-8

### LINKED ISSUE #98: [BUG] Installing impedance.py from source doesn't work
**Describe the bug**
Cloning the repo and installing from source raises `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4236: character maps to <undefined>`

**To Reproduce**
Clone repo:
```
$ git clone https://github.com/ECSHackWeek/impedance.py.git
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 1944 (delta 39), reused 55 (delta 14), pack-reused 1851
Receiving objects: 100% (1944/1944), 5.20 MiB | 10.64 MiB/s, done.
Resolving deltas: 100% (1210/1210), done.
```
Switch to that directory:
`cd impedance.py/`

Try to install:
`python setup.py install --user`

**Expected behavior**
It should successfully install the package
```
running install

...

Using c:\users\shadd\anaconda3\lib\site-packages
Finished processing dependencies for impedance==0.5.1
```

**Additional context**
As suggested in [this thread](https://github.com/minimaxir/textgenrnn/issues/8), changing `with open("README.md", "r") as fh:` to `with open("README.md", "r", encoding='utf8') as fh:` seems to fix the problem.

### PR DESCRIPTION
**Pull request by BGerwe**
Fixes #98

### CODE REVIEW

**Comment by mdmurbach** [comment]
Cool! I wasn't able to verify this since when I tried to install from source it worked (mac), but feel free to merge it in since it fixes the issue! I've also never actually cloned and used setup.py directly to install, but just `pip install .`, have you ever tried that and did that not work either?

**Comment by BGerwe** [comment]
`pip install` works for me just fine, but, if I'm not mistaken, PyPI doesn't update until a new version is released. There are a few features we recently added that my labmates can take advantage of so I want to have them install from source.

**Comment by mdmurbach** [comment]
Sorry, I meant using pip to install from local (you can run `pip install .` in the same directory as setup.py)

**Comment by BGerwe** [comment]
Going that route also fails for me unless the encoding is specified.

**Comment by mdmurbach** [comment]
Interesting! Thanks for testing. Learned something new today 👍

**Pull request merged**
