### PR TITLE
Changed np.complex to just complex in the "fit" function

### PR DESCRIPTION
**Pull request by SaftMacki**
Changed np.complex to just complex in the "fit" function to fix this warning:
DeprecationWarning: np.complex is a deprecated alias for the builtin complex. To silence this warning, use complex by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.complex128 here.
Before:
`if impedance.dtype != np.complex:
     raise TypeError(
         "impedance array should have a complex "
         + f"dtype (currently {impedance.dtype})"
     )`
After:
`if impedance.dtype != complex:
     raise TypeError(
         "impedance array should have a complex "
         + f"dtype (currently {impedance.dtype})"
     )`

### CODE REVIEW

**Comment by SaftMacki** [comment]
@all-contributors please add @SaftMacki for bug fix.

**Comment by SaftMacki** [comment]
Tried to open a new pull request but I think I made a misstake and the new commit is here instead.
I added a line in the preprocessing.py file to replace commas with dots to make it accept when commas is used  as a decimal separator.

**Comment by mdmurbach** [comment]
Hi @SaftMacki and thanks for the PR! It looks like you're using some kind of code cleanup tool like black (the project uses flake8 which conforms to PEP8, but black has a lot of extra formatting preferences) which means that your intended change is mixed into a bunch of formatting changes which makes it hard to review. Would you be able to separate the np.complex change out from all of the indentation and ' to " changes?

Similarly for the second commit to the readGamry function. Can you maybe undo the commit for the changes to the readGamry function and keep that separate to the np.complex change? A `git revert` should do the trick (will make another commit to undue the last commits changes), you can then make the changes on another branch (run git checkout -b <other-branch-name> before committing) and have another PR. Definitely appreciate you bringing the complex warning up and putting together a PR, thank you!

**Comment by SaftMacki** [comment]
Thanks for the answer and explanation. It's my first contribution so I'm happy to learn and correct my misstakes.
I will revert and fix it.

**Comment by SaftMacki** [comment]
Now I hope I got it right.

**Comment by mdmurbach** [comment]
This looks awesome, thanks for making the fix!!

**Pull request merged**
