### PR TITLE
Fixed bug in readZPlot. 

### PR DESCRIPTION
**Pull request by BGerwe**
Also made some changes to preprocessing tests.
*  Condensed expected results inputs
*  Added coverage for readCSV
*  Added coverage for instrument selection in readFile
*  Renamed "Chalco-in-buffer-50mV.DTA" to "exampleDataGamry.DTA"
*  Organized instrument names, example data file paths, and expected results into dictionaries 
*  Truncated data used for testing readZPlot and added an example file without comments in the header

I saw two ways of fixing the readZPlot. One required importing re, the other relies on a bit of error handling to detect what the delimiters are. I ultimately chose the latter, but kept the former approach and commented it out.

### CODE REVIEW

**Comment by BGerwe** [comment]
Addresses issue #72

**Comment by mdmurbach** [comment]
Since `re` is in the standard library, I don't think it's an issue to use it. It is a little cleaner than the try: except in there

**Comment by BGerwe** [comment]
I agree it's much cleaner. I'll double-check the tests locally and push a commit with the `re` version

Thanks for linking the issue! I need to remember that in the future.

**Comment by mdmurbach** [comment]
I think it's new! I just noticed it and clicked to see what it did haha :joy: glad it worked

**Comment by mdmurbach** [comment]
Thanks @BGerwe! :1st_place_medal:

**Pull request merged**
