### PR TITLE
Fix NumPy 2.0 compatibility

### LINKED ISSUE #296: [BUG] NumPy 2.0 seems have broken `impedance.py`
**Describe the bug**
I haven't looked into it very thoroughly but it seems that NumPy 2.0 has changed `float_` to `np.float64` causing the `__repr__` to be slightly different. Bottom line is that `impedance.py`'s `eval_linKK` now complains that `np` is not defined because its inputs for some reason have np.float64(some_number), etc.

**To Reproduce**
Call `eval_linKK`!

**Expected behavior**
That it doesn't throw an Exception.

**Fix**
Add this line:

```python
circuit_elements["np"] = np
```

right before calling `eval` in `eval_linKK`:

```python
def eval_linKK(elements, ts, f):
    """ Builds a circuit of RC elements to be used in LinKK """
    circuit_string = 's([R({},{}),'.format([elements[0]], f.tolist())

    for (Rk, tk) in zip(elements[1:], ts):
        circuit_string += f'K({[Rk, tk]},{f.tolist()}),'

    circuit_string += 'L({},{}),'.format([elements[-1]], f.tolist())
    if elements.size == (ts.size + 3):
        circuit_string += 'C({},{}),'.format([1/elements[-2]], f.tolist())

    circuit_string = circuit_string.strip(',')
    circuit_string += '])'

    # ADD THE FIX HERE  
    return eval(circuit_string, circuit_elements)
```

### PR DESCRIPTION
**Pull request by ma-sadeghi**
Fixes #296

### CODE REVIEW

**Comment by ma-sadeghi** [comment]
@mdmurbach Sorry for tagging, this broke our package, and so we'd appreciate if you review this PR and merge if you agree, thanks :)

**Comment by mdmurbach** [comment]
Thanks for the bug report and PR fix. I think it makes sense to merge in #297 from @BGerwe since that includes tests, but appreciate the find and fix

**Comment by mdmurbach** [comment]
@all-contributors please add @ma-sadeghi for code, bug

**Comment by ma-sadeghi** [comment]
@mdmurbach Thanks for merging the PR! Would you be able to release to PyPI? Thanks!

**Comment by ma-sadeghi** [comment]
Hi @mdmurbach, Could you please make a new release so the NumPy dependency issue is resolved in downstream packages? Thanks in advance!

**Pull request closed without merging**
