### PR TITLE
Add pre-commit config

### PR DESCRIPTION
**Pull request by MattiasMTS**
# What has changed:
* Refactored some logic in `preprocessing.py` because I couldn't resist not to (I was testing the pre-commit logic on this file and just saw it, heh sorry 😋 )
* Added a .pre-commit-config.yaml which includes some nice features that are run before each commit.
  * Remove trailing whitespace (nice to have on default)
  * Consistent end-of-line fixer (might varies depending on OS and stuff).
  * check correct syntax on .yaml and .toml (indentation, etc).
  * check merge-conflict issues before continuing a rebase (nice to have if you do rebase in git)
  * Flake8 linting - checks that the changes you have done are according to the flake8 configuration. Will hopefully reduce unnecessary commits and have a clean git history.
  * mypy checker - nice to have to statically check that the hinted types in the repo is followed. Now I saw that you guys aren't using type hints that much so "if it quacks like a duck, walks like a duck, then it must be a duck!"
  * Prettier formatter on .md/.yaml files - turn e.g. single quotes `'` into double quotes "'" etc.
* Split the `requirement.txt` file into `requirement.txt` and `requirement-dev.txt` files. Depending on if #227 gets merged, I will rebase this PR w.r.t. that one and remove these `.txt` and use `poetry` instead.

### Example of pre-commit for the flake8 checker:
1. Let's say I am making some changes in the `impedance.preprocessing.py` file: 
image
2. I git add and commit this feature with a nice and concise commit message, you will then see the following:
image
I can see that the linting fails on `flake8` with the error messages given there. Note also that the changes I made didn't get committed. I would have to resolve these before proceeding (you can skip this with `--no-verify` command but we keep that secret)
image
And now it allows me to git commit this new change.

### CODE REVIEW

**Comment by MattiasMTS** [comment]
Just saw that the CI is failing due to splitting the `requirements.txt` file. This can be changed depending on #227  . For now, the reviewer can focus on the other changes.

I noticed that the `tests/` folder lives in the `impedance/` folder. Usually, a good practice is to have the `tests` folder _outside_ the actual module folder, since it is focusing on "reflecting" the structure of the module. Furthermore, when you build and ship this package - you then install unnecessary dependency on the user. For example, this package now requires the user to install `pytest` since the `tests` folder uses it. Moving the `tests` folder outside and mirroring the structure of `impedance` allows you to easier decouple some dependencies more. Any thoughts on this @mdmurbach ?

**Comment by mdmurbach** [comment]
> Just saw that the CI is failing due to splitting the `requirements.txt` file. This can be changed depending on #227 . For now, the reviewer can focus on the other changes.
> 
> I noticed that the `tests/` folder lives in the `impedance/` folder. Usually, a good practice is to have the `tests` folder _outside_ the actual module folder, since it is focusing on "reflecting" the structure of the module. Furthermore, when you build and ship this package - you then install unnecessary dependency on the user. For example, this package now requires the user to install `pytest` since the `tests` folder uses it. Moving the `tests` folder outside and mirroring the structure of `impedance` allows you to easier decouple some dependencies more. Any thoughts on this @mdmurbach ?

Yeah, definitely agree (and know now) that putting the tests/ directory at the top level of the repo makes much more sense. Feel free to make that change in this PR or I can follow up after and make that change :)

PS thanks for all of your help recently getting the project from it's early hackweek state to a more robust maintainable package, definitely appreciate it and it's overdue 👍

**Review by mdmurbach — APPROVED** [review]
preprocessing refactor looks great 🐎

**Comment by mdmurbach** [comment]
Going to hold off merging this one in since I think it makes sense to leverage poetry for the requirements

**Pull request closed without merging**
