### PR TITLE
PROPOSAL: Break some stuff in preparation for a v1.0 interface

### PR DESCRIPTION
**Pull request by mdmurbach**
The biggest remaining hurdle before a v1.0 release is making sure that we've got our api in a state that we don't expect it to change much moving forward. To that end, I'd propose a slight reorganization of the modules in `impedance.py` (I know this is going to break some current code, so I think it's worth thinking about this before we do it). Essentially, I've just moved the `circuits` module under a new analysis module (i.e. now its `from impedance.analysis.circuits import CustomCircuit`) in anticipation that we won't have to change the overall api when we eventually add more analysis methods (DRT, physics-based models, etc.). I've also tried to move some more circuit specific methods (saving and loading) to the circuit class itself (now available through `circuit.save(filename)` and `circuit.load(filename)`, so we keep the remaining modules as general as possible.

Curious to get people's thoughts: @lktsui, @BGerwe, @nealde

### CODE REVIEW

**Comment by mdmurbach** [comment]
Another option is to call the analysis module `models`

**Comment by lktsui** [comment]
I have no strong objections to the overall goal of the reorganization effort. 

I think that `models` is a better term to use for the stuff you are proposing to go into the package instead of `analysis`. I think pretty much everything this entire codebase does that touches real data falls into the category of `analysis` and it becomes too vague of a term. I think `models` makes it clear that the things in that package are things that are used to make mathematical representations of the data.

Other packages that might make more sense are a `visualization` package that includes plotting and any potential draw circuit diagram feature (issue #13) that might get added in the future.

**Comment by nealde** [comment]
I think it's fine to break the api in order to more intuitively support feature expansion moving forward - something that may be worth doing is temporarily maintaining the old inheritance through the __init__.py in `analysis` and issuing a deprecation warning. But, totally not a requirement.

I have no strong feelings on models vs analysis, but I like Lok-kun's argument for models.

**Comment by mdmurbach** [comment]
I would tend to agree with you both on the use of models vs analysis. 

The structure of the package would then look like:
Impedance
  - models
    - circuits
  - plotting (rename to visualization?)
  - validation
  - preprocessing
  - model_selection (think it makes sense to add the confidence interval bounds plotting/comparison here)

Any other modules we want to add as placeholders or want to talk about as future additions in the JOSS paper?

That’s a good idea to use a warning with the old structure for any releases from now until 1.0 @nealde (agree that its not a requirement, but might make it easier for someone and it’s not too hard on our end).

**Comment by BGerwe** [comment]
I'm also on board with using `models` instead of analysis. Not sure I fully understand the model_selection angle. Confidence interval bounds make sense for evaluating model goodness of fit, but isn't that just a plotting feature? 

While we are breaking stuff let's also address the circuit element name concerns in #63 . My vote is for two letter element names at a maximum. I expect new additions will be modification to elements we've already added (e.g. finite-length Gerischer) so we can probably get away with an one character modifier

**Comment by mdmurbach** [comment]
Good call on the element naming, dealing with 1 or 2 letter elements should be possible in the current circuit processing scheme, although it's currently set up to just take the first letter as the single-letter element. Someone want to take a crack at implementing two letter elements?
https://github.com/ECSHackWeek/impedance.py/blob/2cd8821fe486c8c5c4a77b30ecce449d1c8d3c38/impedance/fitting.py#L234

In the case of model confidence (deriving confidence bounds from a model and parameter error estimates) it makes sense to me that the code for calculating the intervals lives in a model selection module (we could still have a shortcut conf_bounds argument when plotting). Ultimately, I think the model_selection module would contain a group of functions which take two fit model instances; for example, I think it's where something like an [F-test](https://en.wikipedia.org/wiki/F-test) or other more rigorous model comparison functionality would eventually end up.

**Comment by nealde** [comment]
I'd be happy to take a crack at enabling multi-letter elements, and maybe lowering the barrier to adding new elements in the process (should only need to make a change in one place to update all checking / validation downstream).  Let me know what the process should look like - other than creating a branch, should I open an issue to let people know I'm working on it?

**Comment by mdmurbach** [comment]
Great @nealde! Yeah, it’s probably a good idea to open another issue for that task specifically. I think it makes sense to merge this PR in first, so we don’t end up with crazy merge conflicts down the road. 

I’ll create another issue for the remaining model selection work, but that shouldn’t be affected by anything on the circuit element piece.

**Comment by mdmurbach** [comment]
Yeah, the save/load to/from json was a great idea from @lktsui! :rocket:

**Comment by mdmurbach** [comment]
Think these changes are good to go on my end! (Still some loose ends to tie up -- mostly around model_selection --  but those can be a new PR/issue)

**Pull request merged**
