### PR TITLE
Add non-ideal semi-infinite Warburg element

### PR DESCRIPTION
**Pull request by nobkat**
I have added non-ideal semi-infnite Warburg element.

### CODE REVIEW

**Comment by mdmurbach** [comment]
Great, thanks @nobkat! 😄 Before we pull this in, could you fix the flake8/PEP8 errors that are being flagged by Travis?

```
impedance/circuit_elements.py:135:1: E302 expected 2 blank lines, found 1
impedance/circuit_elements.py:150:1: E302 expected 2 blank lines, found 1
```

You can run the flake8 command on your local copy to check (the output should be nothing)
```bash
conda install flake8
cd impedance.py/
flake8
```

For the documentation, it looks like there's some extra characters in the math equation (I added a comment). Do you have a reference you could add for this element? (see https://github.com/ECSHackWeek/impedance.py/blob/aa370380580ed4e3165a8ed8b49b15e3c48ee392/impedance/circuit_elements.py#L176-L179) for how to add a link.

**Comment by nobkat** [comment]
Thank you very much for reviewing, @mdmurbach .
I have added what you mentioned.

**Comment by BGerwe** [comment]
@all-contributors please add @nobkat for code

**Comment by mdmurbach** [comment]
I just opened a revert PR (#63) for this, but it'd be great to get another PR that we can merge in once we've made these changes.

(copying from #63)
There's a few issues with this one still that need to be fixed before we merge it. In particular,

1. it looks like the reference was added to the incorrect element `W`, https://github.com/ECSHackWeek/impedance.py/blob/18a7920a8d322ff18836afbde27993c21396f85b/impedance/circuit_elements.py#L100-L121 instead of `B` https://github.com/ECSHackWeek/impedance.py/blob/18a7920a8d322ff18836afbde27993c21396f85b/impedance/circuit_elements.py#L140-L153 

2. A quick glance through the reference doesn't show the equation added in `B` (I think). I think it makes sense to either find a different reference or add the equation for blocked diffusion Warburg (Eq. 37) with frequency dispersion that's in this paper.

**Pull request merged**
